/** When your routing table is too long, you can split it into small modules**/
import Layout from '@/layout';

const ujiRoutes = {
  path: '/uji-komp',
  component: Layout,
  redirect: '/uji-komp/list',
  name: 'uji-komp',
  alwaysShow: true,
  meta: {
    title: 'Uji Kompetensi',
    icon: 'documentation',
    permissions: ['view menu administrator'],
  },
  children: [
    {
      path: 'list',
      component: () => import('@/views/back-office/uji/List'),
      name: 'uji-komp-list',
      meta: {
        title: 'List',
        icon: 'list',
        permissions: ['manage user'],
      },
    },
    {
      path: 'history',
      component: () => import('@/views/back-office/uji/History'),
      name: 'history',
      meta: {
        title: 'History',
        icon: 'el-icon-timer',
        permissions: ['manage user'],
      },
    },
    {
      path: 'form-mapa-02',
      component: () => import('@/views/back-office/uji/fr_mapa/02/index'),
      name: 'form-mapa-02',
      meta: {
        title: 'Form MAPA 02',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-apl-01',
      component: () => import('@/views/back-office/uji/fr_apl/01/index'),
      name: 'form-apl-01',
      meta: {
        title: 'Form APL 01',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-apl-02',
      component: () => import('@/views/back-office/uji/fr_apl/02/index'),
      name: 'form-apl-02',
      meta: {
        title: 'Form APL 02',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-01',
      component: () => import('@/views/back-office/uji/fr_ia/01/index'),
      name: 'form-ia-01',
      meta: {
        title: 'Form IA 01',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-02/:id_ia_02/:id_apl_01/:id_skema/:id_uji',
      component: () => import('@/views/back-office/uji/fr_ia/02/index'),
      name: 'form-ia-02',
      meta: {
        title: 'Form IA 02',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-03',
      component: () => import('@/views/back-office/uji/fr_ia/03/index'),
      name: 'form-ia-03',
      meta: {
        title: 'Form IA 03',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-05',
      component: () => import('@/views/back-office/uji/fr_ia/05/index'),
      name: 'form-ia-05',
      meta: {
        title: 'Form IA 05',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-06',
      component: () => import('@/views/back-office/uji/fr_ia/06/index'),
      name: 'form-ia-06',
      meta: {
        title: 'Form IA 06',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-07',
      component: () => import('@/views/back-office/uji/fr_ia/07/index'),
      name: 'form-ia-07',
      meta: {
        title: 'Form IA 07',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ia-11',
      component: () => import('@/views/back-office/uji/fr_ia/11/index'),
      name: 'form-ia-11',
      meta: {
        title: 'Form IA 11',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-01',
      component: () => import('@/views/back-office/uji/fr_ak/01/index'),
      name: 'form-ak-01',
      meta: {
        title: 'Form AK 01',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-02',
      component: () => import('@/views/back-office/uji/fr_ak/02/index'),
      name: 'form-ak-02',
      meta: {
        title: 'Form AK 02',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-03',
      component: () => import('@/views/back-office/uji/fr_ak/03/index'),
      name: 'form-ak-03',
      meta: {
        title: 'Form AK 03',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-04',
      component: () => import('@/views/back-office/uji/fr_ak/04/index'),
      name: 'form-ak-04',
      meta: {
        title: 'Form AK 04',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-05',
      component: () => import('@/views/back-office/uji/fr_ak/05/index'),
      name: 'form-ak-05',
      meta: {
        title: 'Form AK 05',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-06',
      component: () => import('@/views/back-office/uji/fr_ak/06/index'),
      name: 'form-ak-06',
      meta: {
        title: 'Form AK 06',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-ak-07',
      component: () => import('@/views/back-office/uji/fr_ak/07/index'),
      name: 'form-ak-07',
      meta: {
        title: 'Form AK 07',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'preview-ak-07',
      component: () => import('@/views/preview/uji/fr_ak/07/index'),
      name: 'preview-ak-07',
      meta: {
        title: 'Preview AK 07',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'form-va',
      component: () => import('@/views/back-office/uji/fr_va/index'),
      name: 'form-va',
      meta: {
        title: 'Form VA',
        icon: 'date',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'preview-page',
      component: () => import('@/views/preview/index'),
      name: 'preview-page',
      meta: {
        title: 'Preview',
        icon: 'list',
        permissions: ['manage user'],
      },
      hidden: true,
    },
    {
      path: 'preview-apl-01/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_apl/01/index'),
      name: 'preview-apl-01',
      meta: {
        title: 'Preview APL 01',
        icon: 'list',
        permissions: ['manage user'],
        nextPage: 'preview-apl-02',
      },
      hidden: true,
    },
    {
      path: 'preview-apl-02/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_apl/02/index'),
      name: 'preview-apl-02',
      meta: {
        title: 'Preview APL 02',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-apl-01',
        nextPage: 'preview-mapa-02',
      },
      hidden: true,
    },
    {
      path: 'preview-mapa-02/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_mapa/02/index'),
      name: 'preview-mapa-02',
      meta: {
        title: 'Preview MAPA 02',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-apl-02',
        nextPage: 'preview-ak-01',
      },
      hidden: true,
    },
    {
      path: 'preview-ak-01/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ak/01/index'),
      name: 'preview-ak-01',
      meta: {
        title: 'Preview AK 01',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-mapa-02',
        nextPage: 'preview-ak-04',
      },
      hidden: true,
    },
    {
      path: 'preview-ak-04/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ak/04/index'),
      name: 'preview-ak-04',
      meta: {
        title: 'Preview AK 04',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ak-01',
        nextPage: 'preview-ia-01',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-01/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/01/index'),
      name: 'preview-ia-01',
      meta: {
        title: 'Preview IA 01',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ak-04',
        nextPage: 'preview-ia-02',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-02/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/02/index'),
      name: 'preview-ia-02',
      meta: {
        title: 'Preview IA 02',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ia-01',
        nextPage: 'preview-ia-03',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-03/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/03/index'),
      name: 'preview-ia-03',
      meta: {
        title: 'Preview IA 03',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ia-02',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-05/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/05/index'),
      name: 'preview-ia-05',
      meta: {
        title: 'Preview IA 05',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ia-05',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-06/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/06/index'),
      name: 'preview-ia-06',
      meta: {
        title: 'Preview IA 06',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ia-06',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-07/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/07/index'),
      name: 'preview-ia-07',
      meta: {
        title: 'Preview IA 07',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ia-07',
      },
      hidden: true,
    },
    {
      path: 'preview-ia-11/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ia/11/index'),
      name: 'preview-ia-11',
      meta: {
        title: 'Preview IA 11',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ia-11',
      },
      hidden: true,
    },
    {
      path: 'preview-ak-02/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ak/02/index'),
      name: 'preview-ak-02',
      meta: {
        title: 'Preview AK 02',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ak-02',
      },
      hidden: true,
    },
    {
      path: 'preview-ak-03/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ak/03/index'),
      name: 'preview-ak-03',
      meta: {
        title: 'Preview AK 03',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ak-03',
      },
      hidden: true,
    },
    {
      path: 'preview-ak-05/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ak/05/index'),
      name: 'preview-ak-05',
      meta: {
        title: 'Preview AK 05',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ak-05',
      },
      hidden: true,
    },
    {
      path: 'preview-ak-06/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_ak/06/index'),
      name: 'preview-ak-06',
      meta: {
        title: 'Preview AK 06',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-ak-06',
      },
      hidden: true,
    },
    {
      path: 'preview-va/:iduji/:asesor',
      component: () => import('@/views/preview/uji/fr_va/index'),
      name: 'preview-va',
      meta: {
        title: 'Preview VA',
        icon: 'list',
        permissions: ['manage user'],
        previousPage: 'preview-va',
      },
      hidden: true,
    },
  ],
};

export default ujiRoutes;
